version: "3.7"
services:
  jenkins:
    build:
        context: .
        dockerfile: ./Dockerfile.jenkins
        args:
            HOST_UID: ${HOST_UID}
            HOST_GID: ${HOST_GID}
    restart: unless-stopped
    container_name: jenkins
    environment:
        - "JAVA_OPTS=-Xmx3g -Xms2G"
    restart: unless-stopped
    volumes:
        - ${HOST_DOCKER}:/var/run/docker.sock
        - ${HOST_JENKINS_DATA}:/var/jenkins_home
    ports:
        - "${HOST_WWW}:8080"
        - "${HOST_OTHER}:50000"
  s3:
    image: quay.io/minio/minio
    container_name: s3
    volumes:
        - ./buckets:/data:consistent
    expose:
        - "9000"
        - "9001"
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        - MINIO_ROOT_USER=${MINIO_ROOT_USER}
        - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server /data --address ":9000" --console-address ":9001" 
    networks: 
        - mlflow
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
  db:
    restart: always
    image: mysql/mysql-server:5.7.28
    container_name: db
    expose:
        - "3306"
    command: --innodb_use_native_aio=0
    networks: 
        - mlflow
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # volumes:
    #     - ./dbdata:/var/lib/mysql
  mlflow:
    restart: always
    build: ./Dockerfile.mlflow
    image: mlflow_server
    container_name: mlflow_server
    ports:
        - "5000:5000"
    networks: 
        - mlflow
    environment:
        - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
        - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
        - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0
    depends_on: 
        - db
    
networks:
    mlflow: